### ISSUE TITLE
Add hide / show classes for breakpoints

### ISSUE THREAD

**Issue by Zerotask** [pure-css/pure#857] opened 2021-05-30 08:43 UTC
**Is your feature request related to a problem? Please describe.**
I want to hide specific elements on mobile pages. From a previous micro framework (Spectre) I could add `hide-md` which means hide it until it reaches the md breakpoint 767px.
In Bootstrap you could add: `d-none d-md-block` which means it's always hidden, but if it reaches the md breakpoint, it's display block.

**Describe the solution you'd like**
Since there is already a `hidden` class as described here https://purecss.io/base/
> Alternatively, for compatibility with old IE, you may use the CSS classname .hidden.

There could be `show-*` classes. This would allow: `hidden show-md`.

**Describe alternatives you've considered**
The alternative is that I add the classes on my own. Not a big deal, but it's a useful tool when dealing with responsiveness

**Comment by lkraav** [comment] 2021-05-30 12:31
Duplicate of https://github.com/pure-css/pure/issues/640 if not more from further in the past.

**Closed** 2021-08-21 04:17 UTC
Labels: wontfix
